### ISSUE TITLE
When enabling this plugin i cant move overlays by pressing alt

### ISSUE THREAD

**Issue by oeg91** [bluelightzero/unresponsive-cursor#3]
Not sure if its an incompatibility with another plugin, but when i enable this plugin i cant move any overlay like buff, xp orbs etc.

**Comment by bluelightzero** [comment]
@oeg91 I can't reproduce this. I have no issue moving overlays with alt.

Are you using any other cursor changing plugins?

**Comment by thebubbsy** [comment]
hey @bluelightzero i came here about to report a similar issue - its not the moving of info boxes, its the stretching of them.
test by using a SCB pot to get a decent sized info box and attempt to stretch it out longer/shorter. The arrow icon flashes up but is impossible to grab the corner of the info box to adjust. Disable your plugin and not problems
[i made a video where i start with your plugin on, attempt to resize, turn it off and then you quickly see the issue](https://streamable.com/cfol8p)

The Bubbsy#0001 - Is my discord if you want

**Comment by bluelightzero** [comment]
@thebubbsy Sent a FR on discord.

Which Operating system are you using?

The only thing this plugin ever changes is the cursor, so I can only assume DEFAULT_CURSOR is not your default cursor?

Have you noticed your regular cursor has changed? If you click normally is your cursor click offset? (The yellow/red cross that appears when you click)

**Comment by bluelightzero** [comment]
I made a new issue for you here @thebubbsy : https://github.com/bluelightzero/unresponsive-cursor/issues/4

May be diffferent than @oeg91 's issue.

**Comment by oeg91** [comment]
> @oeg91 I can't reproduce this. I have no issue moving overlays with alt.
> 
> Are you using any other cursor changing plugins?

Looks like it was a temporary issue, now i can move any overlay even with custom cursor enable, but i cant resize just like @thebubbsy

**Comment by bluelightzero** [comment]
@oeg91 The fix for resizing should be in v1.1 when that get pulled.

If you get the moving issue again after v1.1 let me know.
